/*
 * @Author: tuWei
 * @Date: 2022-01-19 17:13:36
 * @LastEditors: Please set LastEditors
 * @LastEditTime: 2022-12-14 12:04:33
 */
const oot = {
  /**
   * 药品接口
   */
  auditBaseDrug: { module: 'oot', url: '/goods/drug/auditBase', method: 'POST', comment: '审核基本信息' },
  auditBusinessDrug: { module: 'oot', url: '/goods/drug/auditBusiness', method: 'POST', comment: '审核商务信息' },
  auditImportDrug: { module: 'oot', url: '/goods/drug/auditImport', method: 'POST', comment: '审核进口' },
  auditManualDrug: { module: 'oot', url: '/goods/drug/auditManual', method: 'POST', comment: '审核电子说明书' },
  auditManufacturingDrug: { module: 'oot', url: '/goods/drug/auditManufacturing', method: 'POST', comment: '审核生产信息' },
  auditPackagingDrug: { module: 'oot', url: '/goods/drug/auditPackaging', method: 'POST', comment: '审核包装信息' },
  auditQualityDrug: { module: 'oot', url: '/goods/drug/auditQuality', method: 'POST', comment: '审核质量信息' },
  auditStoreageDrug: { module: 'oot', url: '/goods/drug/auditStoreage', method: 'POST', comment: '审核储运信息' },
  // auditUnit: { module: 'oot', url: '/goods/drug/auditUnit', method: 'POST', comment: '审核单位信息' },
  auditUsageDrug: { module: 'oot', url: '/goods/drug/auditUsage', method: 'POST', comment: '审核使用信息' },
  queryBaseDrug: { module: 'oot', url: '/goods/drug/queryBase', method: 'POST', comment: '查询基本信息' },
  queryManualDrug: { module: 'oot', url: '/goods/drug/queryManual', method: 'POST', comment: '查询电子说明书' },
  queryManufacturingDrug: { module: 'oot', url: '/goods/drug/queryManufacturing', method: 'POST', comment: '查询生产信息' },
  upsertManufacturingDrug: { module: 'oot', url: '/goods/drug/upsertManufacturing', method: 'POST', comment: '创建/更新生产信息' },
  queryPagedDataListDrug: { module: 'oot', url: '/goods/drug/queryPagedDataList', method: 'POST', comment: '查询数据列表' },
  queryStoreageDrug: { module: 'oot', url: '/goods/drug/queryStoreage', method: 'POST', comment: '查询储运信息' },
  queryUsageDrug: { module: 'oot', url: '/goods/drug/queryUsage', method: 'POST', comment: '查询使用信息' },
  upsertBaseDrug: { module: 'oot', url: '/goods/drug/upsertBase', method: 'POST', comment: '创建/更新基本信息' },
  upsertBusinessDrug: { module: 'oot', url: '/goods/drug/upsertBusiness', method: 'POST', comment: '创建/更新商务信息' },
  upsertManualDrug: { module: 'oot', url: '/goods/drug/upsertManual', method: 'POST', comment: '创建/更新点子说明书' },
  upsertPackagingDrug: { module: 'oot', url: '/goods/drug/upsertPackaging', method: 'POST', comment: '创建/更新包装信息' },
  queryQualityDrug: { module: 'oot', url: '/goods/drug/queryQuality', method: 'POST', comment: '查询质量信息' },
  upsertQualityDrug: { module: 'oot', url: '/goods/drug/upsertQuality', method: 'POST', comment: '创建/更新质量信息' },
  upsertStoreageDrug: { module: 'oot', url: '/goods/drug/upsertStoreage', method: 'POST', comment: '创建/更新储运信息' },
  upsertUsageDrug: { module: 'oot', url: '/goods/drug/upsertUsage', method: 'POST', comment: '创建/更新使用信息' },
  queryAdditionalListDrug: { module: 'oot', url: '/goods/drug/queryAdditionalList', method: 'POST', comment: '查询补充信息' },

  //中药饮片
  querySpecialPreparedDrug: { module: 'oot', url: '/goods/drug/querySpecialPreparedDrug', method: 'POST', comment: '查询中药饮片信息' },
  auditSpecialPreparedDrug: { module: 'oot', url: '/goods/drug/auditSpecialPreparedDrug', method: 'POST', comment: '审核中药饮片信息' },
  upsertSpecialPreparedDrug: { module: 'oot', url: '/goods/drug/upsertSpecialPreparedDrug', method: 'POST', comment: '创建/更新中药饮片信息' },

  /**
   * 器械接口
   */
  auditBaseDevice: { module: 'oot', url: '/goods/device/auditBase', method: 'POST', comment: '审核基本信息' },
  auditBusinessDevice: { module: 'oot', url: '/goods/device/auditBusiness', method: 'POST', comment: '审核商务信息' },
  auditImportDevice: { module: 'oot', url: '/goods/device/auditImport', method: 'POST', comment: '审核进口' },
  auditManualDevice: { module: 'oot', url: '/goods/device/auditManual', method: 'POST', comment: '审核电子说明书' },
  auditManufacturingDevice: { module: 'oot', url: '/goods/device/auditManufacturing', method: 'POST', comment: '审核生产信息' },
  auditPackagingDevice: { module: 'oot', url: '/goods/device/auditPackaging', method: 'POST', comment: '审核包装信息' },
  auditQualityDevice: { module: 'oot', url: '/goods/device/auditQuality', method: 'POST', comment: '审核质量信息' },
  auditStoreageDevice: { module: 'oot', url: '/goods/device/auditStoreage', method: 'POST', comment: '审核储运信息' },
  // auditUnit: { module: 'oot', url: '/goods/device/auditUnit', method: 'POST', comment: '审核单位信息' },
  auditUsageDevice: { module: 'oot', url: '/goods/device/auditUsage', method: 'POST', comment: '审核使用信息' },
  queryBaseDevice: { module: 'oot', url: '/goods/device/queryBase', method: 'POST', comment: '查询基本信息' },
  queryManualDevice: { module: 'oot', url: '/goods/device/queryManual', method: 'POST', comment: '查询电子说明书' },
  queryManufacturingDevice: { module: 'oot', url: '/goods/device/queryManufacturing', method: 'POST', comment: '查询生产信息' },
  upsertManufacturingDevice: { module: 'oot', url: '/goods/device/upsertManufacturing', method: 'POST', comment: '创建/更新生产信息' },
  queryPagedDataListDevice: { module: 'oot', url: '/goods/device/queryPagedDataList', method: 'POST', comment: '查询数据列表' },
  queryStoreageDevice: { module: 'oot', url: '/goods/device/queryStoreage', method: 'POST', comment: '查询储运信息' },
  queryUsageDevice: { module: 'oot', url: '/goods/device/queryUsage', method: 'POST', comment: '查询使用信息' },
  upsertBaseDevice: { module: 'oot', url: '/goods/device/upsertBase', method: 'POST', comment: '创建/更新基本信息' },
  upsertBusinessDevice: { module: 'oot', url: '/goods/device/upsertBusiness', method: 'POST', comment: '创建/更新商务信息' },
  upsertManualDevice: { module: 'oot', url: '/goods/device/upsertManual', method: 'POST', comment: '创建/更新点子说明书' },
  upsertPackagingDevice: { module: 'oot', url: '/goods/device/upsertPackaging', method: 'POST', comment: '创建/更新包装信息' },
  queryQualityDevice: { module: 'oot', url: '/goods/device/queryQuality', method: 'POST', comment: '查询质量信息' },
  upsertQualityDevice: { module: 'oot', url: '/goods/device/upsertQuality', method: 'POST', comment: '创建/更新质量信息' },
  upsertStoreageDevice: { module: 'oot', url: '/goods/device/upsertStoreage', method: 'POST', comment: '创建/更新储运信息' },
  upsertUsageDevice: { module: 'oot', url: '/goods/device/upsertUsage', method: 'POST', comment: '创建/更新使用信息' },
  queryAdditionalListDevice: { module: 'oot', url: '/goods/device/queryAdditionalList', method: 'POST', comment: '查询补充信息' },

  /**
   * 食品
   */
   auditBaseFood: { module: 'oot', url: '/goods/food/auditBase', method: 'POST', comment: '审核基本信息' },
   auditBusinessFood: { module: 'oot', url: '/goods/food/auditBusiness', method: 'POST', comment: '审核商务信息' },
   auditImportFood: { module: 'oot', url: '/goods/food/auditImport', method: 'POST', comment: '审核进口' },
   auditManualFood: { module: 'oot', url: '/goods/food/auditManual', method: 'POST', comment: '审核电子说明书' },
   auditManufacturingFood: { module: 'oot', url: '/goods/food/auditManufacturing', method: 'POST', comment: '审核生产信息' },
   auditPackagingFood: { module: 'oot', url: '/goods/food/auditPackaging', method: 'POST', comment: '审核包装信息' },
   auditQualityFood: { module: 'oot', url: '/goods/food/auditQuality', method: 'POST', comment: '审核质量信息' },
   auditStoreageFood: { module: 'oot', url: '/goods/food/auditStoreage', method: 'POST', comment: '审核储运信息' },
  //  auditUnit: { module: 'oot', url: '/goods/food/auditUnit', method: 'POST', comment: '审核单位信息' },
   auditUsageFood: { module: 'oot', url: '/goods/food/auditUsage', method: 'POST', comment: '审核使用信息' },
   queryBaseFood: { module: 'oot', url: '/goods/food/queryBase', method: 'POST', comment: '查询基本信息' },
   queryManualFood: { module: 'oot', url: '/goods/food/queryManual', method: 'POST', comment: '查询电子说明书' },
   queryManufacturingFood: { module: 'oot', url: '/goods/food/queryManufacturing', method: 'POST', comment: '查询生产信息' },
   upsertManufacturingFood: { module: 'oot', url: '/goods/food/upsertManufacturing', method: 'POST', comment: '创建/更新生产信息' },
   queryPagedDataListFood: { module: 'oot', url: '/goods/food/queryPagedDataList', method: 'POST', comment: '查询数据列表' },
   queryStoreageFood: { module: 'oot', url: '/goods/food/queryStoreage', method: 'POST', comment: '查询储运信息' },
   queryUsageFood: { module: 'oot', url: '/goods/food/queryUsage', method: 'POST', comment: '查询使用信息' },
   upsertBaseFood: { module: 'oot', url: '/goods/food/upsertBase', method: 'POST', comment: '创建/更新基本信息' },
   upsertBusinessFood: { module: 'oot', url: '/goods/food/upsertBusiness', method: 'POST', comment: '创建/更新商务信息' },
   upsertManualFood: { module: 'oot', url: '/goods/food/upsertManual', method: 'POST', comment: '创建/更新点子说明书' },
   upsertPackagingFood: { module: 'oot', url: '/goods/food/upsertPackaging', method: 'POST', comment: '创建/更新包装信息' },
   queryQualityFood: { module: 'oot', url: '/goods/food/queryQuality', method: 'POST', comment: '查询质量信息' },
   upsertQualityFood: { module: 'oot', url: '/goods/food/upsertQuality', method: 'POST', comment: '创建/更新质量信息' },
   upsertStoreageFood: { module: 'oot', url: '/goods/food/upsertStoreage', method: 'POST', comment: '创建/更新储运信息' },
   upsertUsageFood: { module: 'oot', url: '/goods/food/upsertUsage', method: 'POST', comment: '创建/更新使用信息' },
   queryAdditionalListFood: { module: 'oot', url: '/goods/food/queryAdditionalList', method: 'POST', comment: '查询补充信息' },

  /**
   * 消毒品
   */
   auditBaseDisinfection: { module: 'oot', url: '/goods/disinfection/auditBase', method: 'POST', comment: '审核基本信息' },
   auditBusinessDisinfection: { module: 'oot', url: '/goods/disinfection/auditBusiness', method: 'POST', comment: '审核商务信息' },
   auditImportDisinfection: { module: 'oot', url: '/goods/disinfection/auditImport', method: 'POST', comment: '审核进口' },
   auditManualDisinfection: { module: 'oot', url: '/goods/disinfection/auditManual', method: 'POST', comment: '审核电子说明书' },
   auditManufacturingDisinfection: { module: 'oot', url: '/goods/disinfection/auditManufacturing', method: 'POST', comment: '审核生产信息' },
   auditPackagingDisinfection: { module: 'oot', url: '/goods/disinfection/auditPackaging', method: 'POST', comment: '审核包装信息' },
   auditQualityDisinfection: { module: 'oot', url: '/goods/disinfection/auditQuality', method: 'POST', comment: '审核质量信息' },
   auditStoreageDisinfection: { module: 'oot', url: '/goods/disinfection/auditStoreage', method: 'POST', comment: '审核储运信息' },
  //  auditUnit: { module: 'oot', url: '/goods/disinfection/auditUnit', method: 'POST', comment: '审核单位信息' },
   auditUsageDisinfection: { module: 'oot', url: '/goods/disinfection/auditUsage', method: 'POST', comment: '审核使用信息' },
   queryBaseDisinfection: { module: 'oot', url: '/goods/disinfection/queryBase', method: 'POST', comment: '查询基本信息' },
   queryManualDisinfection: { module: 'oot', url: '/goods/disinfection/queryManual', method: 'POST', comment: '查询电子说明书' },
   queryManufacturingDisinfection: { module: 'oot', url: '/goods/disinfection/queryManufacturing', method: 'POST', comment: '查询生产信息' },
   upsertManufacturingDisinfection: { module: 'oot', url: '/goods/disinfection/upsertManufacturing', method: 'POST', comment: '创建/更新生产信息' },
   queryPagedDataListDisinfection: { module: 'oot', url: '/goods/disinfection/queryPagedDataList', method: 'POST', comment: '查询数据列表' },
   queryStoreageDisinfection: { module: 'oot', url: '/goods/disinfection/queryStoreage', method: 'POST', comment: '查询储运信息' },
   queryUsageDisinfection: { module: 'oot', url: '/goods/disinfection/queryUsage', method: 'POST', comment: '查询使用信息' },
   upsertBaseDisinfection: { module: 'oot', url: '/goods/disinfection/upsertBase', method: 'POST', comment: '创建/更新基本信息' },
   upsertBusinessDisinfection: { module: 'oot', url: '/goods/disinfection/upsertBusiness', method: 'POST', comment: '创建/更新商务信息' },
   upsertManualDisinfection: { module: 'oot', url: '/goods/disinfection/upsertManual', method: 'POST', comment: '创建/更新点子说明书' },
   upsertPackagingDisinfection: { module: 'oot', url: '/goods/disinfection/upsertPackaging', method: 'POST', comment: '创建/更新包装信息' },
   queryQualityDisinfection: { module: 'oot', url: '/goods/disinfection/queryQuality', method: 'POST', comment: '查询质量信息' },
   upsertQualityDisinfection: { module: 'oot', url: '/goods/disinfection/upsertQuality', method: 'POST', comment: '创建/更新质量信息' },
   upsertStoreageDisinfection: { module: 'oot', url: '/goods/disinfection/upsertStoreage', method: 'POST', comment: '创建/更新储运信息' },
   upsertUsageDisinfection: { module: 'oot', url: '/goods/disinfection/upsertUsage', method: 'POST', comment: '创建/更新使用信息' },
   queryAdditionalListDisinfection: { module: 'oot', url: '/goods/disinfection/queryAdditionalList', method: 'POST', comment: '查询补充信息' },

   /**
   * 化妆品
   */
  auditBaseCosmetics: { module: 'oot', url: '/goods/cosmetics/auditBase', method: 'POST', comment: '审核基本信息' },
  auditBusinessCosmetics: { module: 'oot', url: '/goods/cosmetics/auditBusiness', method: 'POST', comment: '审核商务信息' },
  auditImportCosmetics: { module: 'oot', url: '/goods/cosmetics/auditImport', method: 'POST', comment: '审核进口' },
  auditManualCosmetics: { module: 'oot', url: '/goods/cosmetics/auditManual', method: 'POST', comment: '审核电子说明书' },
  auditManufacturingCosmetics: { module: 'oot', url: '/goods/cosmetics/auditManufacturing', method: 'POST', comment: '审核生产信息' },
  auditPackagingCosmetics: { module: 'oot', url: '/goods/cosmetics/auditPackaging', method: 'POST', comment: '审核包装信息' },
  auditQualityCosmetics: { module: 'oot', url: '/goods/cosmetics/auditQuality', method: 'POST', comment: '审核质量信息' },
  auditStoreageCosmetics: { module: 'oot', url: '/goods/cosmetics/auditStoreage', method: 'POST', comment: '审核储运信息' },
  // auditUnit: { module: 'oot', url: '/goods/cosmetics/auditUnit', method: 'POST', comment: '审核单位信息' },
  auditUsageCosmetics: { module: 'oot', url: '/goods/cosmetics/auditUsage', method: 'POST', comment: '审核使用信息' },
  queryBaseCosmetics: { module: 'oot', url: '/goods/cosmetics/queryBase', method: 'POST', comment: '查询基本信息' },
  queryManualCosmetics: { module: 'oot', url: '/goods/cosmetics/queryManual', method: 'POST', comment: '查询电子说明书' },
  queryManufacturingCosmetics: { module: 'oot', url: '/goods/cosmetics/queryManufacturing', method: 'POST', comment: '查询生产信息' },
  upsertManufacturingCosmetics: { module: 'oot', url: '/goods/cosmetics/upsertManufacturing', method: 'POST', comment: '创建/更新生产信息' },
  queryPagedDataListCosmetics: { module: 'oot', url: '/goods/cosmetics/queryPagedDataList', method: 'POST', comment: '查询数据列表' },
  queryStoreageCosmetics: { module: 'oot', url: '/goods/cosmetics/queryStoreage', method: 'POST', comment: '查询储运信息' },
  queryUsageCosmetics: { module: 'oot', url: '/goods/cosmetics/queryUsage', method: 'POST', comment: '查询使用信息' },
  upsertBaseCosmetics: { module: 'oot', url: '/goods/cosmetics/upsertBase', method: 'POST', comment: '创建/更新基本信息' },
  upsertBusinessCosmetics: { module: 'oot', url: '/goods/cosmetics/upsertBusiness', method: 'POST', comment: '创建/更新商务信息' },
  upsertManualCosmetics: { module: 'oot', url: '/goods/cosmetics/upsertManual', method: 'POST', comment: '创建/更新点子说明书' },
  upsertPackagingCosmetics: { module: 'oot', url: '/goods/cosmetics/upsertPackaging', method: 'POST', comment: '创建/更新包装信息' },
  queryQualityCosmetics: { module: 'oot', url: '/goods/cosmetics/queryQuality', method: 'POST', comment: '查询质量信息' },
  upsertQualityCosmetics: { module: 'oot', url: '/goods/cosmetics/upsertQuality', method: 'POST', comment: '创建/更新质量信息' },
  upsertStoreageCosmetics: { module: 'oot', url: '/goods/cosmetics/upsertStoreage', method: 'POST', comment: '创建/更新储运信息' },
  upsertUsageCosmetics: { module: 'oot', url: '/goods/cosmetics/upsertUsage', method: 'POST', comment: '创建/更新使用信息' },
  queryAdditionalListCosmetics: { module: 'oot', url: '/goods/cosmetics/queryAdditionalList', method: 'POST', comment: '查询补充信息' },
  /**
   * 服务新增
   */
   auditBaseService: { module: 'oot', url: '/service/auditBase', method: 'POST', comment: '服务-审核基本信息' },
   auditBusinessService: { module: 'oot', url: '/service/auditBusiness', method: 'POST', comment: '服务-审核商务信息' },
   auditDeliveryService: { module: 'oot', url: '/service/auditDelivery', method: 'POST', comment: '服务-审核交付信息' },
   auditUsageService: { module: 'oot', url: '/service/auditUsage', method: 'POST', comment: '交易标的中心-服务-审核使用信息' },
   queryBaseService: { module: 'oot', url: '/service/queryBase', method: 'POST', comment: '服务-查询基本信息' },
   serviceListService: { module: 'oot', url: '/service/queryDelivery', method: 'POST', comment: '服务-查询交付信息' },
   queryPagedDataListService: { module: 'oot', url: '/service/queryPagedDataList', method: 'POST', comment: '服务-查询数据列表' },
   queryUsageService: { module: 'oot', url: '/service/queryUsage', method: 'POST', comment: '服务-查询使用信息' },
   upsertBaseService: { module: 'oot', url: '/service/upsertBase', method: 'POST', comment: '服务-创建/更新基本信息' },
   upsertBusinessService: { module: 'oot', url: '/service/upsertBusiness', method: 'POST', comment: '服务-创建/更新商务信息' },
   upsertDeliveryService: { module: 'oot', url: '/service/upsertDelivery', method: 'POST', comment: '服务-创建/更新交付信息' },
   upsertUsageService: { module: 'oot', url: '/service/upsertUsage', method: 'POST', comment: '服务-创建/更新使用信息' },
  /**
   * 其他
   */
   auditBaseOther: { module: 'oot', url: '/goods/other/auditBase', method: 'POST', comment: '审核基本信息' },
   auditBusinessOther: { module: 'oot', url: '/goods/other/auditBusiness', method: 'POST', comment: '审核商务信息' },
   auditImportOther: { module: 'oot', url: '/goods/other/auditImport', method: 'POST', comment: '审核进口' },
  //  auditUnit: { module: 'oot', url: '/goods/other/auditUnit', method: 'POST', comment: '审核单位信息' },
   queryAdditionalListOther: { module: 'oot', url: '/goods/other/queryAdditionalList', method: 'POST', comment: '查询补充信息' },
   queryBaseOther: { module: 'oot', url: '/goods/other/queryBase', method: 'POST', comment: '查询基本信息' },
   queryPagedDataListOther: { module: 'oot', url: '/goods/other/queryPagedDataList', method: 'POST', comment: '查询数据列表' },
   upsertBaseOther: { module: 'oot', url: '/goods/other/upsertBase', method: 'POST', comment: '创建/更新基本信息' },
   upsertBusinessOther: { module: 'oot', url: '/goods/other/upsertBusiness', method: 'POST', comment: '更新商务信息' },
  /**
   * 公共的接口
   */
  queryImport: { module: 'oot', url: '/ext/queryImport', method: 'POST', comment: '查询进口信息' },
  queryLonchErp: { module: 'oot', url: '/ext/queryLonchErp', method: 'POST', comment: '查询NC信息' },
  queryNmpa: { module: 'oot', url: '/ext/queryNmpa', method: 'POST', comment: '查询药监信息' },
  queryUnit: { module: 'oot', url: '/ext/queryUnit', method: 'POST', comment: '查询单位信息' },
  auditUnit: { module: 'oot', url: '/ext/auditUnit', method: 'POST', comment: '审核单位信息' },
  upsertImport: { module: 'oot', url: '/ext/upsertImport', method: 'POST', comment: '创建/更新进口信息' },
  upsertLonchErp: { module: 'oot', url: '/ext/upsertLonchErp', method: 'POST', comment: '创建/更新NC信息' },
  upsertNmpa: { module: 'oot', url: '/ext/upsertNmpa', method: 'POST', comment: '创建/更新药监信息' },
  upsertUnit: { module: 'oot', url: '/ext/upsertUnit', method: 'POST', comment: '创建/更新单位信息' },
  queryMaterialsList: { module: 'oot', url: '/materials/product/queryMaterialsList', method: 'POST', comment: '查询物料列表' },
  queryBarcode: { module: 'oot', url: '/ext/queryBarcode', method: 'POST', comment: '查询条形码信息' },
  upsertBarcode: { module: 'oot', url: '/ext/upsertBarcode', method: 'POST', comment: '创建/更新条形码信息' },
  queryIntroduction: { module: 'oot', url: '/ext/queryIntroduction', method: 'POST', comment: '查询产品图片列表' },
  upsertIntroduction: { module: 'oot', url: '/ext/upsertIntroduction', method: 'POST', comment: '创建/更新图' },
  removeIntroductionVersion: { module: 'oot', url: '/ext/removeIntroductionVersion', method: 'POST', comment: '删除版本图片' },

  /**
   * 业务字典接口
   */
  businessCreate: { module: 'oot', url: '/dic/biz/business/create', method: 'POST', comment: '创建数据项(业务字典-平台商户)' },
  businessDataList: { module: 'oot', url: '/dic/biz/business/queryPagedDataList', method: 'POST', comment: '查询数据项列表(业务字典-平台商户)' },
  businessUpdate: { module: 'oot', url: '/dic/biz/business/update', method: 'POST', comment: '更新数据项(业务字典-平台商户)' },
  cosmeticsTypeCreate: { module: 'oot', url: '/dic/biz/cosmeticsType/create', method: 'POST', comment: '创建数据项(业务字典-化妆品类别)' },
  cosmeticsTypeDataList: { module: 'oot', url: '/dic/biz/cosmeticsType/queryPagedDataList', method: 'POST', comment: '查询数据项列表(业务字典-化妆品类别)' },
  cosmeticsTypeUpdate: { module: 'oot', url: '/dic/biz/cosmeticsType/update', method: 'POST', comment: '更新数据项(业务字典-化妆品类别)' },
  delegateTypeCreate: { module: 'oot', url: '/dic/biz/delegateTypecreate', method: 'POST', comment: '创建数据项(业务字典-委托类型)' },
  delegateTypeList: { module: 'oot', url: '/dic/biz/delegateType/queryPagedDataList', method: 'POST', comment: '查询数据项列表(业务字典-委托类型)' },
  delegateTypeUpdate: { module: 'oot', url: '/dic/biz/delegateType/update', method: 'POST', comment: '更新数据项(业务字典-委托类型)' },
  deviceTypeCreate: { module: 'oot', url: '/dic/biz/deviceType/create', method: 'POST', comment: '创建数据项(业务字典-器械类型)' },
  deviceTypeList: { module: 'oot', url: '/dic/biz/deviceType/queryPagedDataList', method: 'POST', comment: '查询数据项列表(业务字典-器械类型)' },
  deviceTypeUpdate: { module: 'oot', url: '/dic/biz/deviceType/update', method: 'POST', comment: '更新数据项(业务字典-器械类型)' },
  disinfectionTypeCreate: { module: 'oot', url: '/dic/biz/disinfectionType/create', method: 'POST', comment: '创建数据项(业务字典-消毒用品剂型)' },
  disinfectionTypeList: { module: 'oot', url: '/dic/biz/disinfectionType/queryPagedDataList', method: 'POST', comment: '查询数据项列表(业务字典-消毒用品剂型)' },
  disinfectionTypeUpdate: { module: 'oot', url: '/dic/biz/disinfectionType/update', method: 'POST', comment: '更新数据项(业务字典-消毒用品剂型)' },
  drugFormCreate: { module: 'oot', url: '/dic/biz/drugForm/create', method: 'POST', comment: '创建数据项(业务字典-药品剂型)' },
  drugFormList: { module: 'oot', url: '/dic/biz/drugForm/queryPagedDataList', method: 'POST', comment: '查询数据项列表(业务字典-药品剂型)' },
  drugFormUpdate: { module: 'oot', url: '/dic/biz/drugForm/update', method: 'POST', comment: '更新数据项(业务字典-药品剂型)' },
  foodCertMarkCreate: { module: 'oot', url: '/dic/biz/foodCertMark/create', method: 'POST', comment: '创建数据项(业务字典-食品认证标志)' },
  foodCertMarkList:{ module: 'oot', url: '/dic/biz/foodCertMark/queryPagedDataList', method: 'POST', comment: '查询数据项列表(业务字典-食品认证标志)' },
  foodCertMarkUpdate: { module: 'oot', url: '/dic/biz/foodCertMark/update', method: 'POST', comment: '更新数据项(业务字典-食品认证标志)' },
  foodNutriMonitCreate: { module: 'oot', url: '/dic/biz/foodNutriMonit/create', method: 'POST', comment: '创建数据项(业务字典-食品营养检测)' },
  foodNutriMonitList: { module: 'oot', url: '/dic/biz/foodNutriMonit/queryPagedDataList', method: 'POST', comment: '查询数据项列表(业务字典-食品营养检测)' },
  foodNutriMonitUpdate: { module: 'oot', url: '/dic/biz/foodNutriMonit/update', method: 'POST', comment: '更新数据项(业务字典-食品营养检测)' },
  insuCreate:{ module: 'oot', url: '/dic/biz/insu/create', method: 'POST', comment: '创建数据项(业务字典-医保目录)' },
  insuList:{ module: 'oot', url: '/dic/biz/insu/queryPagedDataList', method: 'POST', comment: '查询数据项列表(业务字典-医保目录)' },
  insuUpdate: { module: 'oot', url: '/dic/biz/insu/update', method: 'POST', comment: '更新数据项(业务字典-医保目录)' },
  orgCreate: { module: 'oot', url: '/dic/biz/org/create', method: 'POST', comment: '创建数据项(业务字典-认证机构)' },
  orgList: { module: 'oot', url: '/dic/biz/org/queryPagedDataList', method: 'POST', comment: '查询数据项列表(业务字典-认证机构)' },
  orgQueryList: { module: 'oot', url: '/dic/biz/org/queryList', method: 'POST', comment: '查询企业机构数据' },
  orgUpdate: { module: 'oot', url: '/dic/biz/org/update', method: 'POST', comment: '更新数据项(业务字典-认证机构)' },
  originCreate: { module: 'oot', url: '/dic/biz/origin/create', method: 'POST', comment: '创建数据项(业务字典-产地)' },
  originList: { module: 'oot', url: '/dic/biz/origin/queryPagedDataList', method: 'POST', comment: '查询数据项列表(业务字典-产地)' },
  originUpdate: { module: 'oot', url: '/dic/biz/origin/update', method: 'POST', comment: '更新数据项(业务字典-产地)' },
  otherTypeCreate: { module: 'oot', url: '/dic/biz/otherType/create', method: 'POST', comment: '创建数据项(业务字典-其他产品分类)' },
  otherTypeList: { module: 'oot', url: '/dic/biz/otherType/queryPagedDataList', method: 'POST', comment: '查询数据项列表(业务字典-其他产品分类)' },
  otherTypeUpdate: { module: 'oot', url: '/dic/biz/otherType/update', method: 'POST', comment: '更新数据项(业务字典-其他产品分类)' },
  trademarkCreate: { module: 'oot', url: '/dic/biz/trademark/create', method: 'POST', comment: '创建数据项(业务字典-商标)' },
  trademarkList: { module: 'oot', url: '/dic/biz/trademark/queryPagedDataList', method: 'POST', comment: '查询数据项列表(业务字典-商标)' },
  trademarkUpdate: { module: 'oot', url: '/dic/biz/trademark/update', method: 'POST', comment: '更新数据项(业务字典-商标)' },
  unitCreate: { module: 'oot', url: '/dic/biz/unit/create', method: 'POST', comment: '创建数据项(业务字典-计量单位)' },
  unitList: { module: 'oot', url: '/dic/biz/unit/queryPagedDataList', method: 'POST', comment: '查询数据项列表(业务字典-计量单位)' },
  unitUpdate: { module: 'oot', url: '/dic/biz/unit/update', method: 'POST', comment: '更新数据项(业务字典-计量单位)' },
  sysList: { module: 'oot', url: '/dic/sys/queryPagedDataList', method: 'POST', comment: '查询数据项列表(系统预置)' },
  taxRateList: { module: 'oot', url: '/dic/biz/taxRate/queryPagedDataList', method: 'POST', comment: '查询税率' },
  taxCategoryList: { module: 'oot', url: '/dic/sys/taxCategory/queryPagedDataList', method: 'POST', comment: '查询税收大类' },
  taxCategoryOptList: { module: 'oot', url: '/dic/sys/taxCategory/queryList', method: 'POST', comment: '查询税收大类下拉选择' },
  temperatureRangeList: { module: 'oot', url: '/dic/biz/temperatureRange/queryPagedDataList', method: 'POST', comment: '温度范围查询' },
  temperatureRangeCreate: { module: 'oot', url: '/dic/biz/temperatureRange/create', method: 'POST', comment: '温度范围创建' },
  temperatureRangeUpdate: { module: 'oot', url: '/dic/biz/temperatureRange/update', method: 'POST', comment: '温度范围更新' },
  //医疗卫生机构
  medicalInstTypeList: { module: 'oot', url: '/dic/biz/medicalInstType/queryPagedDataList', method: 'POST', comment: '查询医疗卫生机构分类' },
  medicalInstTypeUpdate: { module: 'oot', url: '/dic/biz/medicalInstType/update', method: 'POST', comment: '更新医疗卫生机构分类' },
  medicalInstTypeCreate: { module: 'oot', url: '/dic/biz/medicalInstType/create', method: 'POST', comment: '创建医疗卫生机构分类' },
  //登记注册类型
  medicalInstRegistrationList: { module: 'oot', url: '/dic/biz/medicalInstRegistration/queryPagedDataList', method: 'POST', comment: '查询登记注册类型' },
  medicalInstRegistrationUpdate: { module: 'oot', url: '/dic/biz/medicalInstRegistration/update', method: 'POST', comment: '更新登记注册类型' },
  medicalInstRegistrationCreate: { module: 'oot', url: '/dic/biz/medicalInstRegistration/create', method: 'POST', comment: '创建登记注册类型' },
  //服务计量单位
  serviceUnitList: { module: 'oot', url: '/dic/biz/serviceUnit/queryPagedDataList', method: 'POST', comment: '查询服务计量单位' },
  serviceUnitUpdate: { module: 'oot', url: '/dic/biz/serviceUnit/update', method: 'POST', comment: '更新服务计量单位' },
  serviceUnitCreate: { module: 'oot', url: '/dic/biz/serviceUnit/create', method: 'POST', comment: '创建服务计量单位' },
  //主办单位
  medicalInstSponsorList: { module: 'oot', url: '/dic/biz/medicalInstSponsor/queryPagedDataList', method: 'POST', comment: '查询主办单位' },
  medicalInstSponsorUpdate: { module: 'oot', url: '/dic/biz/medicalInstSponsor/update', method: 'POST', comment: '更新主办单位' },
  medicalInstSponsorCreate: { module: 'oot', url: '/dic/biz/medicalInstSponsor/create', method: 'POST', comment: '创建主办单位' },
  //管理分类
  medicalInstManageList: { module: 'oot', url: '/dic/biz/medicalInstManage/queryPagedDataList', method: 'POST', comment: '查询分类管理' },
  medicalInstManageUpdate: { module: 'oot', url: '/dic/biz/medicalInstManage/update', method: 'POST', comment: '更新分类管理' },
  medicalInstManageCreate: { module: 'oot', url: '/dic/biz/medicalInstManage/create', method: 'POST', comment: '创建分类管理' },

  //城区市分类
  medicalInstRegionList: { module: 'oot', url: '/dic/biz/medicalInstRegion/queryPagedDataList', method: 'POST', comment: '查询城区市分类' },
  medicalInstRegionUpdate: { module: 'oot', url: '/dic/biz/medicalInstRegion/update', method: 'POST', comment: '更新城区市分类' },
  medicalInstRegionCreate: { module: 'oot', url: '/dic/biz/medicalInstRegion/create', method: 'POST', comment: '创建城区市分类' },

  //交付形式
  deliveryFormList: { module: 'oot', url: '/dic/biz/deliveryForm/queryPagedDataList', method: 'POST', comment: '查询交付形式' },
  deliveryFormUpdate: { module: 'oot', url: '/dic/biz/deliveryForm/update', method: 'POST', comment: '更新交付形式' },
  deliveryFormCreate: { module: 'oot', url: '/dic/biz/deliveryForm/create', method: 'POST', comment: '创建交付形式' },

  //交付方式
  deliveryMethodList: { module: 'oot', url: '/dic/biz/deliveryMethod/queryPagedDataList', method: 'POST', comment: '查询交付方式' },
  deliveryMethodUpdate: { module: 'oot', url: '/dic/biz/deliveryMethod/update', method: 'POST', comment: '更新交付方式' },
  deliveryMethodCreate: { module: 'oot', url: '/dic/biz/deliveryMethod/create', method: 'POST', comment: '创建交付方式' },

  inOutMethodQueryList: { module: 'oot', url: '/dic/biz/inOutMethod/queryList', method: 'POST', comment: '出入库方式列表' },
  //资产
  queryPagedAsset: { module: 'oot', url: '/open/queryPagedAsset', method: 'POST', comment: '查询资产标的' },
  //标的对外标准输出
  queryPagedCosmetics: { module: 'oot', url: '/open/queryPagedCosmetics', method: 'POST', comment: '查询化妆品信息' },
  queryPagedDevice: { module: 'oot', url: '/open/queryPagedDevice', method: 'POST', comment: '查询器械信息' },
  queryPagedDisinfection: { module: 'oot', url: '/open/queryPagedDisinfection', method: 'POST', comment: '查询消毒用品信息' },
  queryPagedDrug: { module: 'oot', url: '/open/queryPagedDrug', method: 'POST', comment: '查询药品信息' },
  queryPagedFood: { module: 'oot', url: '/open/queryPagedFood', method: 'POST', comment: '查询食品信息' },
  queryPagedOther: { module: 'oot', url: '/open/queryPagedOther', method: 'POST', comment: '查询其他商品信息' },
  queryPagedService: { module: 'oot', url: '/open/queryPagedService', method: 'POST', comment: '查询服务标的信息' },
  //盘点字典
  countingMethodList: { module: 'oot', url: '/dic/biz/countingMethod/queryList', method: 'POST', comment: '盘点方式列表' },
  countingTypeList: { module: 'oot', url: '/dic/biz/countingType/queryList', method: 'POST', comment: '盘点类型列表' },
  countingCycleList: { module: 'oot', url: '/dic/biz/countingCycle/queryList', method: 'POST', comment: '盘点周期列表' },
  /**
   * 商品发布管理
  */
   goodsPubUpsertApply: { module: 'oot', url: '/goods/pub/upsertApply', method: 'POST', comment: '创建/更新商品发布申请' },
   goodsPubQueryPagedApplyList: { module: 'oot', url: '/goods/pub/queryPagedApplyList', method: 'POST', comment: '查询商品发布申请列表' },
   goodsPubQueryApply: { module: 'oot', url: '/goods/pub/queryApply', method: 'POST', comment: '查询商品发布申请详情' },
   goodsPubAuditApply: { module: 'oot', url: '/goods/pub/auditApply', method: 'POST', comment: '审核商品发布申请' },

   queryObjects: { module: 'oot', url: '/open/queryObjects', method: 'POST', comment: '查询标的的信息' },
   searchObjects: { module: 'oot', url: '/open/searchObjects', method: 'POST', comment: '查询标的的信息' },
}

export default oot;
